version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: todo_list
      DB_USER: root
      DB_PASSWORD: root

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_list
    ports:
      - "3306:3306"

      
